server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_db
    username: erpuser
    password: erp1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

